# Form implementation generated from reading ui file 'Calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_calc(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.label_result = QtWidgets.QLabel(parent=Form)
        self.label_result.setGeometry(QtCore.QRect(40, 310, 500, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(40, 20, 531, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_first_num = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_first_num.setFont(font)
        self.label_first_num.setObjectName("label_first_num")
        self.horizontalLayout.addWidget(self.label_first_num)
        self.lineEdit_first_num = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_first_num.setFont(font)
        self.lineEdit_first_num.setObjectName("lineEdit_first_num")
        self.horizontalLayout.addWidget(self.lineEdit_first_num)

        self.pushButton_menu = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_menu.setFont(font)
        self.pushButton_menu.setObjectName("pushButton_menu")
        self.verticalLayout.addWidget(self.pushButton_menu)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_second_num = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_second_num.setFont(font)
        self.label_second_num.setObjectName("label_second_num")
        self.horizontalLayout_2.addWidget(self.label_second_num)
        self.lineEdit_second_num = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_second_num.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_second_num.setFont(font)
        self.lineEdit_second_num.setObjectName("lineEdit_second_num")
        self.horizontalLayout_2.addWidget(self.lineEdit_second_num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Add = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Add.setFont(font)
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.pushButton_Add.clicked.connect(self.add)
        self.horizontalLayout_3.addWidget(self.pushButton_Add)
        self.pushButton_Minus = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Minus.setFont(font)
        self.pushButton_Minus.setObjectName("pushButton_Minus")
        self.pushButton_Minus.clicked.connect(self.minus)
        self.horizontalLayout_3.addWidget(self.pushButton_Minus)
        self.pushButton_Multi = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Multi.setFont(font)
        self.pushButton_Multi.setObjectName("pushButton_Multi")
        self.pushButton_Multi.clicked.connect(self.multiply)
        self.horizontalLayout_3.addWidget(self.pushButton_Multi)
        self.pushButton_Divi = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Divi.setFont(font)
        self.pushButton_Divi.setObjectName("pushButton_Divi")
        self.pushButton_Divi.clicked.connect(self.divide)
        self.horizontalLayout_3.addWidget(self.pushButton_Divi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def add(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num + second_num
        self.label_result.setText("Addition : {} ".format(result))

    def minus(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num - second_num
        self.label_result.setText("Minus : {} ".format(result))

    def multiply(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num * second_num
        self.label_result.setText("Multiplication : {} ".format(result))

    def divide(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num / second_num
        self.label_result.setText("Divide : {} ".format(result))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Simple Calc"))
        self.label_first_num.setText(_translate("Form", "First Number:"))
        self.lineEdit_first_num.setPlaceholderText(_translate("Form", "Enter First Number"))
        self.label_second_num.setText(_translate("Form", "Second Number:"))
        self.lineEdit_second_num.setPlaceholderText(_translate("Form", "Enter Second Number"))

        self.pushButton_menu.setText(_translate("Form", "Menu"))

        self.pushButton_Add.setText(_translate("Form", "+"))
        self.pushButton_Minus.setText(_translate("Form", "-"))
        self.pushButton_Multi.setText(_translate("Form", "*"))
        self.pushButton_Divi.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)  # 使尺寸一致
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_calc()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
