# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frametest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Frametest_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 370)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 50, 471, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 438, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hbox_choose = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hbox_choose.setContentsMargins(0, 0, 0, 0)
        self.hbox_choose.setSpacing(5)
        self.hbox_choose.setObjectName("hbox_choose")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_choose.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_speed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed.setFont(font)
        self.label_speed.setObjectName("label_speed")
        self.horizontalLayout.addWidget(self.label_speed)
        self.spinBox_speed = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_speed.setFont(font)
        self.spinBox_speed.setObjectName("spinBox_speed")
        self.horizontalLayout.addWidget(self.spinBox_speed)
        self.hbox_choose.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_style = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_style.setFont(font)
        self.label_style.setObjectName("label_style")
        self.horizontalLayout_2.addWidget(self.label_style)
        self.comboBox_style = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_style.setFont(font)
        self.comboBox_style.setObjectName("comboBox_style")
        self.horizontalLayout_2.addWidget(self.comboBox_style)
        self.hbox_choose.addLayout(self.horizontalLayout_2)
        self.label_section = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_section.setFont(font)
        self.label_section.setObjectName("label_section")
        self.hbox_choose.addWidget(self.label_section)
        self.spinBox_section = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_section.setFont(font)
        self.spinBox_section.setObjectName("spinBox_section")
        self.hbox_choose.addWidget(self.spinBox_section)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_choose.addItem(spacerItem1)
        self.hbox_choose.setStretch(1, 5)
        self.hbox_choose.setStretch(2, 5)
        self.hbox_choose.setStretch(3, 2)
        self.hbox_choose.setStretch(4, 3)
        self.hbox_choose.setStretch(5, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_speed.setText(_translate("Form", "速度："))
        self.label_style.setText(_translate("Form", "风格："))
        self.label_section.setText(_translate("Form", "小节："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Frametest_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
